"""
============================================================
TP53 RAG Platform - Agent #9: The Medical Auditor
============================================================
Verifies every clinical output before it reaches a clinician
or patient. Implements the exact verification protocol from
the hackathon strategy document.

This agent is what wins the Safety & Trust $10k track.

It checks for:
  - Pharmacological hallucinations
  - Contextual drift (Western-centric recommendations)
  - Racial/ethnic bias (African population variants)
  - Ungrounded therapeutic claims

Architecture:
  Agent output + RAG source snippets
    → Auditor (Gemma 4 strict mode)
    → APPROVED or REJECTED with reasoning
    → If REJECTED → re-generation with constraints
============================================================
"""

from typing import Dict, Any, Optional
from dataclasses import dataclass
from agents.rag_chain import TP53RAGChain
from utils.logger import log


# ── Exact auditor prompt from strategy document ───────────
# Enhanced with African population context
AUDITOR_SYSTEM_PROMPT = """### SYSTEM INSTRUCTION: MEDICAL AUDITOR & VERIFICATION AGENT (AGENT #9)

ROLE: You are an elite, hyper-critical clinical medical auditor verifying automated insights 
generated by a Clinical Decision Support System (CDSS) for oncology operating in Kenya, 
East Africa. Your sole purpose is to ruthlessly eliminate medical hallucinations, ungrounded 
diagnostic claims, or unsafe therapeutic suggestions.

CRITICAL OPERATIONAL RULES:

1. STRICT GROUNDING: You must compare the generated [PROPOSED CLINICAL OUTPUT] 
against the raw text snippets provided in the [RETRIEVED EVIDENCE CONTEXT]. 
Every therapeutic claim must be explicitly traceable to the evidence.

2. ZERO TOLERANCE: If the proposed output makes ANY therapeutic recommendation, 
drug dosage, or survival probability assertion that is NOT explicitly supported by the 
retrieved context, you MUST flag it as a critical failure.

3. CONTEXT RESTRICTION: Do not use your own internal pre-trained medical knowledge 
to validate ungrounded claims. If the retrieved evidence does not state it, it does not exist.

4. AFRICAN POPULATION AWARENESS: You must actively check whether any flagged variant 
has known high allele frequency in East African or sub-Saharan African populations. 
If a variant is common and benign in African populations but flagged as pathogenic by 
Western-trained databases, this is a CRITICAL RACIAL BIAS ERROR requiring immediate flagging.

5. LOCAL RESOURCE ALIGNMENT: Therapeutic recommendations must reflect real-world 
availability in Kenya. References to drugs unavailable in the Kenya Essential Medicines 
List without acknowledging local alternatives constitutes CONTEXTUAL DRIFT.

EVALUATION PROTOCOL:
Analyse the proposed output step-by-step for the following violations:

- PHARMACOLOGICAL HALLUCINATION: Recommending a drug or compound not explicitly 
  linked to the variant in the evidence.
- CONTEXTUAL DRIFT: Recommending Western-centric treatment pathways when local 
  geographic constraints apply.
- RACIAL/ETHNIC BIAS OVERLOOK: Failing to highlight if a variant is highly prevalent 
  and benign in African populations as noted in local frequency data.
- DOSAGE FABRICATION: Specifying any drug dosage not present in the source evidence.
- SURVIVAL STATISTICS: Quoting survival rates or probabilities not in the evidence.

OUTPUT FORMAT — follow this exact structure, no introductory phrases:

### [AUDIT STATUS: APPROVED / REJECTED]

*Reasoning Matrix:*
- Grounding Score: [0-10, where 10 = every clause matches a cited snippet]
- Patient Safety Risk: [None / Low / Severe]
- Local Resource Alignment: [Aligned / Misaligned]
- African Population Bias Check: [Clear / Flag Raised]

*Flagged Contradictions / Hallucinations:*
- [If none, write "None". If present, quote the exact problematic sentence 
  and explain why it lacks grounding in the source material.]

*Corrected Output Loop Instruction:*
- [Precise, highly constrained instruction for the primary agent to re-synthesise safely.]"""


@dataclass
class AuditResult:
    """Structured output from the Auditor agent."""
    status: str           # "APPROVED" or "REJECTED"
    grounding_score: int  # 0-10
    patient_safety_risk: str
    local_resource_alignment: str
    african_bias_check: str
    flagged_issues: str
    correction_instruction: str
    raw_audit: str
    original_output: str
    attempts: int = 1


class AuditorAgent:
    """
    Agent #9 — The Medical Auditor.

    Every clinical output passes through here before
    reaching a clinician or patient. No exceptions.

    Max 2 re-generation attempts before flagging for
    human review.
    """

    MAX_ATTEMPTS = 2

    def __init__(self, rag_chain: TP53RAGChain):
        self.rag_chain = rag_chain
        log.info("AuditorAgent (#9) initialised — zero tolerance mode active")

    def audit(
        self,
        proposed_output: str,
        retrieved_sources: list,
        agent_name: str = "unknown",
    ) -> AuditResult:
        """
        Audit a proposed clinical output against its sources.

        Args:
            proposed_output: Text generated by any clinical agent
            retrieved_sources: RAG source documents used to generate it
            agent_name: Which agent produced this output

        Returns:
            AuditResult with APPROVED/REJECTED status
        """
        log.info(f"Auditing output from agent: {agent_name}")

        context = self._format_sources(retrieved_sources)
        audit_response = self._run_audit(proposed_output, context)
        result = self._parse_audit(audit_response, proposed_output)

        if result.status == "APPROVED":
            log.info(f"Audit APPROVED | agent={agent_name} | score={result.grounding_score}/10")
        else:
            log.warning(
                f"Audit REJECTED | agent={agent_name} | "
                f"risk={result.patient_safety_risk} | "
                f"issues={result.flagged_issues[:100]}"
            )

        return result

    def audit_and_regenerate(
        self,
        proposed_output: str,
        retrieved_sources: list,
        regeneration_fn,
        agent_name: str = "unknown",
    ) -> Dict[str, Any]:
        """
        Audit output. If rejected, trigger regeneration with constraints.
        Max 2 attempts.

        Args:
            proposed_output: Initial agent output
            retrieved_sources: RAG sources
            regeneration_fn: Callable that takes correction_instruction → new output
            agent_name: Which agent produced this

        Returns:
            Dict with final_output, audit_result, attempts_needed
        """
        current_output = proposed_output
        attempts = 0

        while attempts < self.MAX_ATTEMPTS:
            attempts += 1
            result = self.audit(current_output, retrieved_sources, agent_name)

            if result.status == "APPROVED":
                return {
                    "final_output": current_output,
                    "audit_result": result,
                    "attempts_needed": attempts,
                    "auto_approved": True,
                }

            if attempts < self.MAX_ATTEMPTS and result.correction_instruction:
                log.info(f"Regenerating with correction (attempt {attempts+1})...")
                try:
                    current_output = regeneration_fn(result.correction_instruction)
                except Exception as e:
                    log.error(f"Regeneration failed: {e}")
                    break

        # Max attempts reached — flag for human review
        log.warning(f"Max audit attempts reached for {agent_name} — flagging for human review")
        return {
            "final_output": current_output,
            "audit_result": result,
            "attempts_needed": attempts,
            "auto_approved": False,
            "requires_human_review": True,
        }

    def _run_audit(self, proposed_output: str, context: str) -> str:
        """Run the audit via Gemma 4."""
        try:
            from langchain.prompts import ChatPromptTemplate
            from langchain_core.output_parsers import StrOutputParser

            prompt = ChatPromptTemplate.from_messages([
                ("system", AUDITOR_SYSTEM_PROMPT),
                ("human", """[PROPOSED CLINICAL OUTPUT]:
{proposed_output}

[RETRIEVED EVIDENCE CONTEXT]:
{context}

Audit the proposed output now. Follow the exact output format specified."""),
            ])

            chain = prompt | self.rag_chain.llm | StrOutputParser()
            return chain.invoke({
                "proposed_output": proposed_output,
                "context": context,
            })
        except Exception as e:
            log.error(f"Audit execution failed: {e}")
            return f"### [AUDIT STATUS: REJECTED]\n*Reasoning Matrix:*\n- Grounding Score: 0\n- Patient Safety Risk: Severe\n- Local Resource Alignment: Misaligned\n- African Population Bias Check: Unknown\n*Flagged Contradictions / Hallucinations:*\n- Audit system error: {e}\n*Corrected Output Loop Instruction:*\n- Retry after system recovery."

    def _parse_audit(self, audit_text: str, original: str) -> AuditResult:
        """Parse the structured audit response."""
        status = "APPROVED" if "APPROVED" in audit_text.upper() else "REJECTED"

        def extract(label, default="Unknown"):
            for line in audit_text.split("\n"):
                if label.lower() in line.lower():
                    parts = line.split(":")
                    if len(parts) > 1:
                        return parts[-1].strip().strip("[]")
            return default

        return AuditResult(
            status=status,
            grounding_score=int(extract("Grounding Score", "5").split("/")[0].strip()
                                if "/" in extract("Grounding Score", "5")
                                else extract("Grounding Score", "5").split()[0]),
            patient_safety_risk=extract("Patient Safety Risk", "Unknown"),
            local_resource_alignment=extract("Local Resource Alignment", "Unknown"),
            african_bias_check=extract("African Population Bias Check", "Unknown"),
            flagged_issues=self._extract_section(audit_text, "Flagged Contradictions"),
            correction_instruction=self._extract_section(audit_text, "Corrected Output"),
            raw_audit=audit_text,
            original_output=original,
        )

    def _extract_section(self, text: str, section_name: str) -> str:
        """Extract a section from the audit response."""
        lines = text.split("\n")
        capturing = False
        result = []
        for line in lines:
            if section_name.lower() in line.lower():
                capturing = True
                continue
            if capturing:
                if line.startswith("*") and section_name.lower() not in line.lower():
                    break
                if line.strip():
                    result.append(line.strip("- ").strip())
        return " ".join(result) if result else "None"

    def _format_sources(self, sources: list) -> str:
        """Format RAG sources for the audit prompt."""
        if not sources:
            return "No source documents retrieved — all claims are ungrounded."
        parts = []
        for i, src in enumerate(sources[:5], 1):
            if isinstance(src, dict):
                content = src.get("content_preview", src.get("content", str(src)))
                category = src.get("category", "unknown")
                score = src.get("relevance_score", 0)
            else:
                content = str(src)
                category = "unknown"
                score = 0
            parts.append(
                f"[Evidence {i} | Category: {category} | "
                f"Relevance: {score}]\n{content}"
            )
        return "\n\n---\n\n".join(parts)
