"""
============================================================
Precision Onco Africa - Multimodal Case Fusion
agents/multimodal_fusion.py
============================================================
Combines whatever evidence the clinician has gathered across the platform —
a TP53 variant, a Gemma-vision pathology-slide narration, a photographed
lab-report reading, a Sanger .ab1 finding, and free-text clinical notes —
into a single, unified case summary generated by the LLM.

Honest by construction:
  * It synthesises ONLY the modalities actually provided; it never invents a
    finding for a modality that is absent (and it says which were used).
  * It is decision-support, not a diagnosis: the prompt and the output both
    carry the research-use-only framing and an explicit uncertainty section.
  * Zero inputs -> a clear "nothing to fuse yet" result, never a fabricated
    summary.

The LLM is injected (a rag_chain with .query, or any callable) so this is
fully unit-testable without a live model.
"""
from __future__ import annotations

from typing import Callable, Dict, List, Optional

from utils.logger import log

FUSION_DISCLAIMER = ("Unified research-use-only synthesis of the evidence you "
                     "provided — not a diagnosis. Confirm every element against "
                     "its source and a qualified clinician.")

# (input key, human label) — order defines how the case is presented.
_MODALITIES = [
    ("mutation", "TP53 variant"),
    ("cancer", "Cancer type"),
    ("vaf", "Variant allele frequency"),
    ("pathology_narration", "Pathology slide (Gemma vision)"),
    ("lab_report_summary", "Photographed lab report (Gemma vision)"),
    ("sanger_summary", "Sanger .ab1 chromatogram"),
    ("notes", "Clinician notes"),
]

_FUSION_SYSTEM_PROMPT = (
    "You are a precision-oncology copilot synthesising a multimodal case for a "
    "clinician in a low-resource setting. Integrate ONLY the evidence provided "
    "below into a single, concise case summary. Do not invent findings for any "
    "modality that is absent. Structure the answer as: (1) Case at a glance, "
    "(2) What the combined evidence suggests, (3) What remains uncertain or "
    "unconfirmed. Be explicit about uncertainty. This is decision-support, not "
    "a diagnosis."
)


def _present_modalities(inputs: Dict) -> List[str]:
    used = []
    for key, label in _MODALITIES:
        val = inputs.get(key)
        if val is None:
            continue
        if isinstance(val, str) and not val.strip():
            continue
        used.append(label)
    return used


def _build_case_text(inputs: Dict) -> str:
    lines = []
    for key, label in _MODALITIES:
        val = inputs.get(key)
        if val is None:
            continue
        if isinstance(val, str) and not val.strip():
            continue
        lines.append(f"- {label}: {val}")
    return "\n".join(lines)


def fuse_case(inputs: Dict,
              llm: Optional[object] = None,
              generate_fn: Optional[Callable[[str, str], str]] = None) -> Dict:
    """Fuse the provided modalities into one unified summary.

    inputs: dict keyed by the modality keys in _MODALITIES.
    llm: optional object exposing `.query(question, agent_type=...)` (e.g. the
         TP53RAGChain). generate_fn: optional (system_prompt, user_prompt)->str.
         If neither is given, falls back to building the default backend.

    Never raises.
    """
    used = _present_modalities(inputs)
    if not used:
        return {"success": False,
                "reason": "No evidence provided yet — add a variant, a slide "
                          "reading, a Sanger result, or notes first.",
                "modalities_used": []}

    case_text = _build_case_text(inputs)
    user_prompt = (f"CASE EVIDENCE:\n{case_text}\n\n"
                   "Synthesise the unified case summary now.")

    try:
        if generate_fn is not None:
            summary = generate_fn(_FUSION_SYSTEM_PROMPT, user_prompt)
        elif llm is not None and hasattr(llm, "query"):
            res = llm.query(
                question=(f"{_FUSION_SYSTEM_PROMPT}\n\n{user_prompt}"),
                agent_type="clinical_interpretation")
            summary = res.get("answer", "") if isinstance(res, dict) else str(res)
        else:
            from agents.rag_chain import _build_backend
            backend = _build_backend()
            summary = backend.generate(_FUSION_SYSTEM_PROMPT, user_prompt,
                                       max_tokens=768)
    except Exception as e:
        log.error(f"Multimodal fusion failed: {e}")
        return {"success": False, "reason": str(e), "modalities_used": used}

    summary = (summary or "").strip()
    if not summary:
        return {"success": False,
                "reason": "The model returned an empty synthesis.",
                "modalities_used": used}

    return {"success": True, "summary": summary, "modalities_used": used,
            "disclaimer": FUSION_DISCLAIMER}
