"""
TP53 RAG Platform - Clinical PDF Report Generator
Professional printable report for tumor board meetings.
Uses reportlab — pure Python, 100% offline.
"""

from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional
from utils.logger import log


def generate_pdf_report(
    accession: str,
    pipeline_data: Dict[str, Any],
    agent_results: Dict[str, Any],
    multilingual_results: Optional[Dict[str, str]] = None,
    drug_results: Optional[Dict[str, Any]] = None,
    audit_results: Optional[Dict] = None,
    output_dir: str = "data/reports",
) -> str:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib.colors import HexColor, black, white, darkred
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table,
            TableStyle, HRFlowable, PageBreak
        )
        from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
    except ImportError:
        log.error("reportlab not installed. Run: pip install reportlab")
        return ""

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{output_dir}/tp53_report_{accession}_{ts}.pdf"
    now = datetime.now().strftime("%B %d, %Y at %H:%M")

    doc = SimpleDocTemplate(filename, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)

    DARK = HexColor("#0d1821")
    TEAL = HexColor("#00d4ff")
    GREY = HexColor("#4a7a8a")
    LIGHT = HexColor("#f0f7fa")
    MID = HexColor("#e0eef5")

    styles = getSampleStyleSheet()
    title_s = ParagraphStyle("T", fontName="Helvetica-Bold", fontSize=20,
                              textColor=DARK, spaceAfter=4)
    sub_s = ParagraphStyle("S", fontName="Helvetica", fontSize=9,
                            textColor=GREY, spaceAfter=2)
    section_s = ParagraphStyle("H", fontName="Helvetica-Bold", fontSize=11,
                                textColor=TEAL, spaceBefore=12, spaceAfter=4)
    body_s = ParagraphStyle("B", fontName="Helvetica", fontSize=9,
                             textColor=DARK, leading=14, spaceAfter=6,
                             alignment=TA_JUSTIFY)
    warn_s = ParagraphStyle("W", fontName="Helvetica-Bold", fontSize=8,
                             textColor=darkred, spaceAfter=4)
    sw_s = ParagraphStyle("SW", fontName="Helvetica", fontSize=9,
                           textColor=DARK, leading=14, spaceAfter=6,
                           backColor=MID, borderPad=8)

    story = []
    mutations = pipeline_data.get("mutations", [])
    hotspot_set = {"R175H","R248W","R248Q","R273H","R273C","G245S","R249S","R282W"}
    hotspots = [m for m in mutations
                if m.get("amino_acid_change","") in hotspot_set]

    # ── Cover ──────────────────────────────────────────────
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph("TP53 Genomic Analysis Report", title_s))
    story.append(Paragraph(
        f"Accession: {accession}  ·  Generated: {now}  ·  "
        f"Platform: TP53 RAG v1.0 (Gemma 4 + Ollama)", sub_s))
    story.append(HRFlowable(width="100%", thickness=2, color=TEAL, spaceAfter=10))
    story.append(Paragraph(
        "⚠ FOR RESEARCH AND CLINICAL DECISION SUPPORT ONLY. "
        "All findings must be confirmed by a CLIA-certified laboratory. "
        "This report was generated by an AI system and requires clinician review.",
        warn_s))

    # ── Summary table ──────────────────────────────────────
    story.append(Paragraph("EXECUTIVE SUMMARY", section_s))
    tdata = [
        ["Parameter", "Value"],
        ["Accession ID", accession],
        ["Sequence Length", f"{pipeline_data.get('sequence_length','—')} bp"],
        ["GC Content", f"{pipeline_data.get('gc_content','—')}%"],
        ["Total Mutations", str(len(mutations))],
        ["Hotspot Mutations", str(len(hotspots))],
        ["Analysis Model", "Gemma 4 (local, Ollama)"],
        ["Report Generated", now],
    ]
    t = Table(tdata, colWidths=[5*cm, 11*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),DARK),("TEXTCOLOR",(0,0),(-1,0),white),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,-1),9),
        ("ROWBACKGROUNDS",(0,1),(-1,-1),[white,LIGHT]),
        ("GRID",(0,0),(-1,-1),0.5,GREY),("PADDING",(0,0),(-1,-1),6),
        ("FONTNAME",(0,1),(0,-1),"Helvetica-Bold"),
    ]))
    story.append(t)

    # ── Mutations table ────────────────────────────────────
    if mutations:
        story.append(Paragraph("MUTATIONS DETECTED", section_s))
        mdata = [["Position","Change","AA Change","Classification"]]
        for m in mutations:
            aa = m.get("amino_acid_change","—")
            mdata.append([
                str(m.get("position","")),
                f"{m.get('original','?')}→{m.get('mutant','?')}",
                aa,
                "HOTSPOT ⚠" if aa in hotspot_set else "Non-hotspot",
            ])
        mt = Table(mdata, colWidths=[3*cm,4*cm,4*cm,5*cm])
        mt.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),DARK),("TEXTCOLOR",(0,0),(-1,0),white),
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,-1),8),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[white,LIGHT]),
            ("GRID",(0,0),(-1,-1),0.5,GREY),("PADDING",(0,0),(-1,-1),5),
        ]))
        story.append(mt)

    # ── Agent sections ─────────────────────────────────────
    for key, title in [
        ("mutation_analysis","MUTATION ANALYSIS"),
        ("clinical_interpretation","CLINICAL INTERPRETATION"),
        ("domain_annotation","PROTEIN DOMAIN ANNOTATION"),
        ("phylogenetic_analysis","PHYLOGENETIC CONSERVATION"),
    ]:
        result = agent_results.get(key)
        if not result:
            continue
        answer = result.answer if hasattr(result,"answer") else str(result)
        if answer and len(answer) > 20:
            story.append(Paragraph(title, section_s))
            story.append(Paragraph(answer[:1000], body_s))

    # ── Audit status ───────────────────────────────────────
    if audit_results:
        story.append(Paragraph("AI VERIFICATION AUDIT", section_s))
        for agent_name, audit in audit_results.items():
            if hasattr(audit, "status"):
                status_color = "green" if audit.status == "APPROVED" else "red"
                story.append(Paragraph(
                    f"{agent_name}: {audit.status} | "
                    f"Grounding: {audit.grounding_score}/10 | "
                    f"Safety Risk: {audit.patient_safety_risk}",
                    body_s
                ))

    # ── Drug discovery ─────────────────────────────────────
    if drug_results:
        story.append(PageBreak())
        story.append(Paragraph("DRUG DISCOVERY & THERAPEUTIC INSIGHTS", section_s))
        story.append(Paragraph(
            drug_results.get("drug_insights","")[:1000], body_s))
        if drug_results.get("resistance_profile"):
            story.append(Paragraph("CHEMOTHERAPY RESISTANCE PROFILE", section_s))
            story.append(Paragraph(
                drug_results["resistance_profile"][:600], body_s))
        if drug_results.get("kenya_availability"):
            story.append(Paragraph("KENYA MEDICINES AVAILABILITY", section_s))
            story.append(Paragraph(
                drug_results["kenya_availability"][:400], body_s))

    # ── Patient reports ────────────────────────────────────
    if multilingual_results:
        story.append(PageBreak())
        story.append(Paragraph("PATIENT INFORMATION (English)", section_s))
        story.append(Paragraph(
            multilingual_results.get("patient_report_en","")[:800], body_s))
        story.append(Spacer(1, 0.5*cm))
        story.append(Paragraph("TAARIFA KWA MGONJWA (Kiswahili)", section_s))
        story.append(Paragraph(
            multilingual_results.get("patient_report_sw","")[:800], sw_s))

    # ── Footer ─────────────────────────────────────────────
    story.append(Spacer(1, 0.8*cm))
    story.append(HRFlowable(width="100%", thickness=1, color=GREY))
    story.append(Paragraph(
        f"Generated by TP53 RAG Platform v1.0 · Gemma 4 (Ollama) · "
        f"100% Local · No Patient Data Transmitted · {now}", sub_s))

    doc.build(story)
    log.info(f"PDF report saved: {filename}")
    return filename
