"""
============================================================
CODE_MAP.md generator
tools/gen_code_map.py
============================================================
Walks the codebase and emits CODE_MAP.md — one entry per module with its
purpose (module docstring) and public API (top-level classes/functions with
signatures + one-line summaries). A fast way to re-orient in the project
months later without reading every file.

Run: python tools/gen_code_map.py     (writes CODE_MAP.md at the repo root)
Pure ast parsing — no imports/execution of the target modules.
"""
from __future__ import annotations

import ast
from pathlib import Path
from typing import List, Optional

ROOT = Path(__file__).resolve().parent.parent
PACKAGES = ["agents", "utils", "knowledge_base", "config", "api", "tools",
            "benchmarks"]
SKIP = {"__pycache__", "__init__.py"}


def _first_sentence(doc: Optional[str], limit: int = 240) -> str:
    if not doc:
        return ""
    text = " ".join(doc.strip().split())
    # drop the decorative banner lines if present
    for junk in ("===", "Precision Onco Africa -"):
        if junk in text:
            text = text.split("===")[-1].strip()
            break
    if len(text) > limit:
        text = text[:limit].rsplit(" ", 1)[0] + "…"
    return text


def _sig(node: ast.FunctionDef) -> str:
    args = []
    a = node.args
    posonly = getattr(a, "posonlyargs", [])
    for arg in posonly + a.args:
        args.append(arg.arg)
    if a.vararg:
        args.append("*" + a.vararg.arg)
    for arg in a.kwonlyargs:
        args.append(arg.arg)
    if a.kwarg:
        args.append("**" + a.kwarg.arg)
    args = [x for x in args if x != "self"]
    return f"{node.name}({', '.join(args)})"


def _public(name: str) -> bool:
    return not name.startswith("_")


def module_entry(path: Path) -> str:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except Exception:
        return ""
    rel = path.relative_to(ROOT).as_posix()
    lines = [f"### `{rel}`", ""]
    doc = _first_sentence(ast.get_docstring(tree))
    if doc:
        lines += [doc, ""]
    api: List[str] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and _public(node.name):
            d = _first_sentence(ast.get_docstring(node), 120)
            methods = [_sig(m) for m in node.body
                       if isinstance(m, ast.FunctionDef) and _public(m.name)]
            api.append(f"- **class `{node.name}`** — {d}"
                       + (f"  · methods: {', '.join(methods[:8])}" if methods else ""))
        elif isinstance(node, ast.FunctionDef) and _public(node.name):
            d = _first_sentence(ast.get_docstring(node), 120)
            api.append(f"- `{_sig(node)}` — {d}" if d else f"- `{_sig(node)}`")
    if api:
        lines += api
    else:
        lines.append("_(no public API)_")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    out = ["# CODE_MAP — module reference",
           "",
           "_Auto-generated by `tools/gen_code_map.py` (re-run to refresh)._ ",
           "One entry per module: its purpose + public API. For architecture "
           "and data flow see [ARCHITECTURE.md](ARCHITECTURE.md); for the maths "
           "see [METHODS.md](METHODS.md).",
           ""]
    total = 0
    for pkg in PACKAGES:
        pdir = ROOT / pkg
        if not pdir.is_dir():
            continue
        files = sorted(f for f in pdir.rglob("*.py")
                       if not any(s in f.parts for s in SKIP)
                       and f.name not in SKIP)
        if not files:
            continue
        out.append(f"## {pkg}/")
        out.append("")
        for f in files:
            entry = module_entry(f)
            if entry:
                out.append(entry)
                total += 1
    out.insert(4, f"**{total} modules** across {len(PACKAGES)} packages.\n")
    (ROOT / "CODE_MAP.md").write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote CODE_MAP.md ({total} modules)")


if __name__ == "__main__":
    main()
